name: BSInstruments
version: 1.0
main: biraw.online.bSInstruments.BSInstruments
api-version: 1.21

commands:
  geti:
    description: Get an instrument by name
    usage: /geti <name>
    permission: bsinstruments.geti
    permission-message: You don't have permission to use this command!

permissions:
  bsinstruments.geti:
    description: Allows the player to use /geti
    default: op
